//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PesonalFilesOfStudents.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecordBook()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> DateOfPassing { get; set; }
        public Nullable<int> Mark { get; set; }
        public string Teacher { get; set; }
        public int StudentID { get; set; }
    
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
