//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PesonalFilesOfStudents.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ReadingBooks = new HashSet<ReadingBook>();
            this.RecordBooks = new HashSet<RecordBook>();
        }
    
        public int StudentID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Registration { get; set; }
        public int Course { get; set; }
        public int Group { get; set; }
        public string Faculty { get; set; }
        public string Gender { get; set; }
        public int RecordBookID { get; set; }
        public int ReadingBookID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadingBook> ReadingBooks { get; set; }
        public virtual ReadingBook ReadingBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordBook> RecordBooks { get; set; }
        public virtual RecordBook RecordBook { get; set; }
    }
}
